apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-pod
  template:
    metadata:
      labels:
        app: catalog-pod
    spec:
      containers:
      - name: catalog-container
        image: sandeepsoni/eshop-catalog
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent      
        envFrom:        
          - secretRef:
             name: catalog-mysecret 

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-srv
spec:
  type: ClusterIP
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-mysecret
type: Opaque
data:
  ConnectionStrings__ProductCatalogApiContext: U2VydmVyPW1zc3Fsc2VydmVyLXNydjtEYXRhYmFzZT1DYXRhbG9nRGI7VXNlciBJZD1zYTtQYXNzd29yZD1QYXNzd29yZF8xMjM=