apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc-pod
  template:
    metadata:
      labels:
        app: webmvc-pod
    spec:
      containers:
      - name: webmvc-container
        image: sandeepsoni/eshop-webapp
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        envFrom:        
          - configMapRef:
             name: webapp-configmap                   
        # env:
        # - name: CatalogUrl
        #   value: "http://gateway-srv/c"
        # - name: CartUrl
        #   value: "http://gateway-srv/b"
        # - name: IdentityServerUrl
        #   value: "http://identity-srv"
 
---

apiVersion: v1
kind: Service
metadata:
  name: webmvc-srv
spec:
  type: LoadBalancer
  selector:
    app: webmvc-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
data:
  CatalogUrl: "http://gateway-srv/c"  
  CartUrl: "http://gateway-srv/b"
  IdentityServerUrl: "http://identity-srv"